CREATE TABLE IF NOT EXISTS `USER`(
    `ID` VARCHAR(255)  default random_uuid() NOT NULL,
    `NAME` VARCHAR(30) NOT NULL,
    `EMAIL` VARCHAR(30) NOT NULL,
    `PASSWORD` VARCHAR(30) NOT NULL,
    `CREATED` DATE NOT NULL,
    `MODIFIED` DATE NULL,
    `LAST_LOGIN` DATE NULL,
    `TOKEN` VARCHAR(255) NOT NULL,
    `IS_ACTIVE` BOOLEAN DEFAULT TRUE NOT NULL,
    PRIMARY KEY (`ID`)
);$$$


CREATE TABLE IF NOT EXISTS `PHONE`(
    `ID` INT NOT NULL,
    `NUMBER` VARCHAR(30) NOT NULL,
    `CITY_CODE` VARCHAR(30) NOT NULL,
    `COUNTRY_CODE` VARCHAR(30)NOT NULL,
    `ID_USER` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID`)
);$$$


ALTER TABLE `PHONE`
    ADD FOREIGN KEY (`ID_USER`)
        REFERENCES `USER` (`ID`);$$$

DROP SEQUENCE IF EXISTS `PHONE_SEQ`; $$$

create sequence `PHONE_SEQ` start with 1 increment by 1;$$$
